on:
  push:
    branches:
      - '**'

jobs:
  build-job:
    name: Build Firmware
    runs-on: ubuntu-latest
#   container:
#      image: xeenych/arm-none-eabi:10.3

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
            cd out
            cmake ../ -DVERSION=${{ github.run_number }}
            cmake --build .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: out/Debug
